### PR TITLE
Set helm chart ownership to team hydra

### PR DESCRIPTION
**Pull request by fiunchinho**
This PR:

- sets helm chart ownership to team hydra

### Checklist

- [X] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by bavarianbidi — COMMENTED** [review]
What about `clippy` for `capz` and `rocket` for `capo` / `capvcd`?

**Review by whites11 — APPROVED** [review]

**Comment by fiunchinho** [comment]
> What about `clippy` for `capz` and `rocket` for `capo` / `capvcd`?

Each app has its own owner, so `capz` owner needs to be `clippy`, the same way `capo` owner needs to be `rocket`.

In this PR I'm just setting what was decided on [the ownership spreadsheet](https://docs.google.com/spreadsheets/d/1GNXAbYo_HyjjRusd2KTGttuORBkX9iMdgnNp-xTQ9sw/edit#gid=0).

**Comment by bavarianbidi** [comment]
> > What about `clippy` for `capz` and `rocket` for `capo` / `capvcd`?
> 
> Each app has its own owner, so `capz` owner needs to be `clippy`, the same way `capo` owner needs to be `rocket`.
> 
> In this PR I'm just setting what was decided on [the ownership spreadsheet](https://docs.google.com/spreadsheets/d/1GNXAbYo_HyjjRusd2KTGttuORBkX9iMdgnNp-xTQ9sw/edit#gid=0).

@fiunchinho 
sorry, my comment was a bit misleading.

According to [giantswarm/github](https://github.com/giantswarm/github/blob/master/repositories/area-kaas.yaml#LL2-L8C19) the app belongs to `area-kaas`.

Maybe i'm wrong but how i understand this PR:
As long as we don't change the `CODEOWNERS` via `giantswarm/github`, the only change will be, that the team-annotation label will be `hydra` - no matter if CAPI is deployed in a `CAPZ`/`CAPO`/`CAPVCD` MC, or am i wrong?

**Comment by fiunchinho** [comment]
[I'm also updating the `github` repo to change the `CODEOWNERS`](https://github.com/giantswarm/github/pull/710). I believe that the team annotation label is the same on all providers. Should it be different?

**Comment by fiunchinho** [comment]
ok, I understand what you mean now. I pushed a change to set the ownership to both rocket and hydra. I believe that if we remove this line `# generated by giantswarm/github actions - changes will be overwritten` our github automation will leave this file alone and keep its contents intact. What do you think?

**Comment by fiunchinho** [comment]
According to our intranet, we use the team annotation for alerting, and IIUC we can route alerts to different teams depending the provider. So I just pushed some changes to specify a different owner based on the provider. Please, take a look.

**Comment by bavarianbidi** [comment]
> ok, I understand what you mean now. I pushed a change to set the ownership to both rocket and hydra now. I believe that if we remove this line `# generated by giantswarm/github actions - changes will be overwritten` our github automation will leave this file alone and keep its contents intact. What do you think?

i know absolutely nothing about `giantswarm/github` repo (beside the configuration there) - so let's find it out :sweat_smile:

**Review by bavarianbidi — APPROVED** [review]

**Comment by fiunchinho** [comment]
> > ok, I understand what you mean now. I pushed a change to set the ownership to both rocket and hydra now. I believe that if we remove this line `# generated by giantswarm/github actions - changes will be overwritten` our github automation will leave this file alone and keep its contents intact. What do you think?
> 
> i know absolutely nothing about `giantswarm/github` repo (beside the configuration there) - so let's find it out sweat_smile

That's what [I understand here](https://github.com/giantswarm/github/blob/master/.github/action/index.js#L359-L365). But we will find out soon enough :smile:

**Pull request merged**
