### PR TITLE
Added make target to generate values schema

### PR DESCRIPTION
**Pull request by AverageMarcus**
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>

This PR:

- adds/changes/removes etc

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by glitchcrab** [comment]
This is dangerous - it's very easy to introduce issues involving `null` values into the schema which only manifest when you try and install the chart later on. The generated schema absolutely has to be eyeballed afterwards because the schema is only as good as your values file. 

My concern with making it an automated step like this is that people just fire and forget.

**Comment by AverageMarcus** [comment]
Are people hand-writing the schema files?

The schema still goes into the commit and is part of the pull request. Is that not enough?

(I also have no idea what makes use of the schema file)

**Comment by AverageMarcus** [comment]
@glitchcrab I decided to have it show the diff after generating.

**Comment by AverageMarcus** [comment]
> The most important thing is not to have any values in the schema which are null only.

Can we not add a PR check for that?

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
