### PR TITLE
update CAPI to version v1.2.2

### PR DESCRIPTION
**Pull request by bavarianbidi**
This PR:

- adds/changes/removes etc

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by fiunchinho** [comment]
I don't think CAPG is compatible with that version of CAPI just yet. As for CAPA, we would have to upgrade it I guess

- [We use CAPA 1.5.0](https://github.com/giantswarm/cluster-api-provider-aws-app/blob/master/helm/cluster-api-provider-aws/values.yaml#L2), and it seems to be compatible with [CAPI 1.1.5](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/v1.5.0/go.mod)
- [We use CAPG 1.1.1](https://github.com/giantswarm/cluster-api-provider-gcp-app/blob/main/helm/cluster-api-provider-gcp/values.yaml#L2) and it seems to be compatible with [CAPI 1.1.5](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/v1.1.1/go.mod#L20).

**Comment by fiunchinho** [comment]
We are now using a CAPG version that is compatible with CAPI `v1.2.x`. So I'd say let's upgrade CAPI. Can you move forward with this @bavarianbidi ?

**Comment by bavarianbidi** [comment]
> We are now using a CAPG version that is compatible with CAPI `v1.2.x`. So I'd say let's upgrade CAPI. Can you move forward with this @bavarianbidi ?

Unfourtanetly there is no CAPI `v1.2.x` compatible `CAPO` version there. And i guess same applies for `CAPVCD`.

**Comment by fiunchinho** [comment]
I'm thinking that maybe we can release this as a new major version of the app, and manually deploying it where it makes sense / it's needed. We need it in AWS and GCP to use of [`skipPhases` that got merged on `v1.2.0`](https://github.com/kubernetes-sigs/cluster-api/pull/5993).
Since this app is not automatically pushed to all collections when releasing, I think it should be doable. What do you think?

**Comment by bavarianbidi** [comment]
> I'm thinking that maybe we can release this as a new major version of the app, and manually deploying it where it makes sense / it's needed. We need it in AWS and GCP to use of [`skipPhases` that got merged on `v1.2.0`](https://github.com/kubernetes-sigs/cluster-api/pull/5993). Since this app is not automatically pushed to all collections when releasing, I think it should be doable. What do you think?

I think it's fine for doing this update.

**Pull request merged**
